# Extract the IQ codebooks from llama.cpp's ggml-common.h into src/quant_tables.h.
# Usage: python tools/gen_tables.py <path to ggml-common.h>
import re, sys, pathlib

src = pathlib.Path(sys.argv[1]).read_text(encoding="utf-8")
want = ["iq2xxs_grid", "iq2xs_grid", "iq2s_grid", "iq3xxs_grid", "iq3s_grid", "kvalues_iq4nl", "iq1s_grid_gpu"]
out = []
out.append("// Generated by tools/gen_tables.py from llama.cpp ggml/src/ggml-common.h. Do not edit.\n"
           "// Copyright (c) 2023-2026 The ggml authors. MIT License (see THIRD_PARTY_NOTICES.md).\n"
           "#pragma once\n#include <cstdint>\n\nnamespace q27 {\n")
for name in want:
    m = re.search(r"GGML_TABLE_BEGIN\((\w+),\s*" + name + r",\s*(\w+)\)(.*?)GGML_TABLE_END\(\)", src, re.S)
    if not m:
        sys.exit("table not found: " + name)
    ctype, size, body = m.group(1), m.group(2), m.group(3)
    vals = re.findall(r"-?0x[0-9a-fA-F]+|-?\d+", body)
    n = {"NGRID_IQ1S": 2048}.get(size, None) or int(size)
    if len(vals) != n:
        sys.exit(f"{name}: expected {n} values, got {len(vals)}")
    out.append(f"inline constexpr {ctype} {name}[{n}] = {{")
    for i in range(0, n, 8):
        out.append("    " + ", ".join(vals[i:i + 8]) + ",")
    out.append("};\n")
out.append("}  // namespace q27\n")
pathlib.Path("src/quant_tables.h").write_text("\n".join(out), encoding="utf-8")
print("wrote src/quant_tables.h")
